project:
  type: book
  
# the [incidence of payroll taxes](taxes/payroll_mobility_tax.qmd#incidence)  
  
# https://quarto.org/docs/computations/execution-options.html    
# for cell options: https://quarto.org/docs/reference/cells/cells-knitr.html
execute:
  eval: true
  echo: false
  error: false
  warning: false
  message: false  # not sure if allowed
  note: false  # not sure if allowed  
  
editor_options: 
  chunk_output_type: console  

book:
  title: "Potential Impact of Declines in San Francisco Property Values"
  author: "Don Boyd"
  date: today
  date-format: long
  chapters:
    - index.qmd
    - highlights.qmd
    - office_vacancies.qmd
    - sanfran_hit_worse.qmd
    - economy_notes.qmd
    - budget_finance_hearing.qmd
    - bibliography.qmd

bibliography: _bibliography.bib
nocite: |
  @*

format:
  html:
    theme: cosmo
  docx:
    toc: true
    toc-depth: 2
    number-sections: true
    highlight-style: github
    reference-doc: refdoc.docx
  # pdf:
  #   documentclass: scrreprt

editor: source

# web 
#   site: https://vacancies-crankstart.netlify.app/
#   password: mndjb

