# Budget and Finance Committee Hearing, November 16, 2022

On November 16, the Budget and Finance Committee of the Board of Supervisors, at its regular meeting, included a hearing on two related topics: (1) economic impact of vacanices and reduced daytime population in the city's economic core, and (2) future of commercial real estate and its impact on the economy and tax revenue. The primary focus was the Financial District, SOMA, and Embarcadero.

The hearing was chaired by Supervisor Hillary Ronen and held at the joint request of Supervisor Asha Safai and Supervisor Catherine Stefani (who is not on the committee but joined the meeting). Supervisors Connie Chan, Safai, and Stefani were particularly engaged and are likely to be leaders in responses to the property value declines.

The hearing is a good source of information, so I provide some links below:

-   [Hearing landing page](https://sanfrancisco.granicus.com/player/clip/42495?view_id=7&redirect=true&h=741f7d80c405950380ccc6be4dd3d3e2)

-   [Video download](javascript:swapIndexContent('download');https://archive-video.granicus.com/sanfrancisco/sanfrancisco_95d859c6-4165-46a1-8658-3eab5499b8e1.mp4)

-   [Letter of request](https://sfgov.legistar.com/View.ashx?M=F&ID=11450535&GUID=00762A07-7976-4C4A-A378-01D64A19DDAE) from Supervisor Stefani. Note that she is aware that potential impacts go beyond the property tax, and stated: "Prior to the pandemic, the downtown area was responsible for generating more than 45% of the city's sales tax. Since then, the neighborhood has seen some of the largest declines in sales tax revenue, with some ZIP codes experiencing a more than 50% drop between 2019 and 2021."

-   [Presentation](https://sfgov.legistar.com/View.ashx?M=F&ID=11458420&GUID=6A6BA06C-4C41-402C-91E5-45C4D93A0348) by Ted Egan, Chief Economist, Office of the Controller. This is particularly good. It begins shortly after 1:59:00 in the video.

-   [Presentation](https://sfgov.legistar.com/View.ashx?M=F&ID=11459856&GUID=2E9C3D48-7164-4243-9EE5-58FF80EFCE11) and [letter of response](https://sfgov.legistar.com/View.ashx?M=F&ID=11450533&GUID=174067F0-6FB5-421F-ADE3-5CA6929C8929) from Joaquín Torres, San Francisco Assessor-Recorder.

-   [Presentation](https://sfgov.legistar.com/View.ashx?M=F&ID=11459459&GUID=FF583FEA-C48C-41E4-914E-72CF868AB1B6) by Alistair Gibson, Assessment Appeals Board.

