# Highlights

## Multiple taxes will be hit, and multiple elements of the property tax will be hit

-   The decline in property values will affect not just the property tax, but also business taxes (such as the gross receipts tax), the property transfer tax, and the sales tax.

-   The revenue hit will be largest for the property tax, but impacts may be felt *sooner* for other taxes.


## Property tax impact will be stretched out and muted by Proposition 13 rules and industry practices

The rules for reassessing properties when market values decline are important because they control the timing and magnitude of changse in assessments and tax revenue:

    -   Most properties currently are assessed below market because Proposition 13's 2% annual growth limit means assessments have not kept up with market values.
    
    -   Assessments will only go down when market values fall so far that they are below assessed values. Thus, the city has a "cushion" of underassessment - only a part of the market value drop will lead to assessment drops.

    -   When market values drop below assessed value, assessed values of commercial properties generally are not automatically reduced. Assessment reductions are triggered by:

        -   A sale of the property for a low price that suggests market value is below assessed value, or
        
        -   A successful appeal of assessment by the property owner, alleging that market value is below the assessed value.
        
    -   This makes appeals very important.
    Typical thisRather, the property owner must appeal the assessment.

    -   Two things can trigger this appeal: (1) a sale of the property for a price that suggests market value is below assessed value

    -   def

    -   ghi

-   Within the property tax, focus has been on vacant office buildings but other elements of the property tax will be affected negatively, too.

## The crisis is likely to be prolonged

## Policies matter

-   An important question is whether, how, and when

## San Francisco has been hit harder than most other cities and will recover more slowly

-   Office vacancy rates are likely to rise further, remain high for along time, and come down slowly.

-   All major cities are being hit by sharp rises in vacancy rates, but San Francisco is among the hardest hit, and vacancy rates are likely to fall more slowly. SF hit harder than South Bay.

## Some members the Board of Supervisors are intensely focused on these issues

-   Several Supervisors are paying close attention to these issues. For more, see a relevant [Budget and Finance Committee hearing](budget_finance_hearing.qmd).

## Timetable

-   The controller's chief economist has estimated the potential property tax impact of office vacancies but the controller's office has not yet done a full re-estimate of revenue including the rest of the property tax and other revenue sources.

-   The controller's office expects to prepare revised estimates for the full budget, mulitple taxes and multiple years, by December 10 or shortly thereafter.

-   These will help the Mayor decide what instructions to issue to city departments in December as they prepare their budget requests for 2023-24 and beyond. (For example, should they plan to cut spending by x?)

-   This kicks off the budget process for 2023-24, which starts July 1, 2023. Key dates: (1) February 22, 2023 - requests from departments become public, (2) May 1: Mayor's proposal to the Board of Supervisors for selected departments, (3) June 1: Mayor's proposal for the full budget, and (4) July 29: final deadline for the Board of Supervisors to adopt the budget. (See this [schedule](https://sf.gov/step-by-step/budget-process-timeline).)

-   Thus, the key policymaking period for the next budget starts publicly in about 2 weeks and runs through July.
